spring.application.name=Backend-I

spring.datasource.url=jdbc:postgresql://major-database.cfyosgeayjkq.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=yashharshil

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.auto-commit=false
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thummaryash969@gmail.com
spring.mail.password=pjxedvapjfnyqbgr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

whatsapp.token=EAASBorlb8AUBRARgiPW355Mb5gIagjelVDT8jtrzOVe4ydP2E11qhwjRDMY9mZAiYPcgMlhtEhMXyeIkqckJm9LUQvXkzD2GXMuuqITQP53fEJglfh44hm3bc7bJydrFBDk5YUMc2tO7tEV6wym5SrgF83DveViH3ziQEyoOLvIH7VfCniIaOHJaBrTLUQcyijXKehAZCbWtmKSxD3LQdJb77w3EiedbZBA0xWr
whatsapp.phone-id=1109356838921528

server.port=5000